// <auto-generated />
namespace Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class HasDefaultSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HasDefaultSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "201506250457057_HasDefaultSchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
