// <auto-generated />
namespace Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MealPlanDatamodelupdated10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MealPlanDatamodelupdated10));
        
        string IMigrationMetadata.Id
        {
            get { return "201506291904407_MealPlanData model updated 10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
