// <auto-generated />
namespace Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Vote_Object_and_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Vote_Object_and_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201506300322395_Vote_Object_and_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
