// <auto-generated />
namespace Meal_Planner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class added_table_MealPlan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_table_MealPlan));
        
        string IMigrationMetadata.Id
        {
            get { return "201506250120150_added_table_MealPlan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
